apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aurora.fullname" . }}-celery-beat
  labels:
    {{- include "aurora.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCounts.celeryBeat }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "aurora.name" . }}-celery-beat
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ include "aurora.name" . }}-celery-beat
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/part-of: aurora
    spec:
      containers:
        - name: celery-beat
          image: "{{ .Values.image.registry }}/aurora-server:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          command: ["celery", "-A", "celery_config", "beat", "--loglevel=info"]
          envFrom:
            - configMapRef:
                name: {{ include "aurora.fullname" . }}-config
            - secretRef:
                name: {{ include "aurora.fullname" . }}-secrets
          resources:
            {{- toYaml .Values.resources.celeryBeat | nindent 12 }}
