apiVersion: v1
kind: Service
metadata:
  name: {{ include "aurora.fullname" . }}-chatbot
  labels:
    {{- include "aurora.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "aurora.name" . }}-chatbot
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: ws
      port: 5006
      targetPort: 5006
    - name: health
      port: 5007
      targetPort: 5007
