apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aurora.fullname" . }}-frontend
  labels:
    {{- include "aurora.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCounts.frontend }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "aurora.name" . }}-frontend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ include "aurora.name" . }}-frontend
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/part-of: aurora
    spec:
      containers:
        - name: aurora-frontend
          image: "{{ .Values.image.registry }}/aurora-frontend:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
          envFrom:
            - configMapRef:
                name: {{ include "aurora.fullname" . }}-config
            - secretRef:
                name: {{ include "aurora.fullname" . }}-secrets
          env:
            - name: NODE_ENV
              value: "production"
          resources:
            {{- toYaml .Values.resources.frontend | nindent 12 }}
