apiVersion: v1
kind: Service
metadata:
  name: {{ include "aurora.fullname" . }}-postgres
  labels:
    {{- include "aurora.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "aurora.name" . }}-postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
