apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aurora.fullname" . }}-secrets-backend
  labels:
    {{- include "aurora.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $key, $value := .Values.secrets.backend }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
