apiVersion: v1
kind: Service
metadata:
  name: {{ include "aurora.fullname" . }}-t2v-transformers
  labels:
    {{- include "aurora.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "aurora.name" . }}-t2v-transformers
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 8080
      targetPort: 8080
