{{- if .Values.services.weaviate.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "aurora.fullname" . }}-weaviate
  labels:
    {{- include "aurora.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "aurora.fullname" . }}-weaviate
  replicas: {{ .Values.replicaCounts.weaviate }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "aurora.name" . }}-weaviate
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "aurora.name" . }}-weaviate
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/part-of: aurora
    spec:
      automountServiceAccountToken: false
      containers:
        - name: weaviate
          image: cr.weaviate.io/semitechnologies/weaviate:1.27.6
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
            - name: grpc
              containerPort: 50051
          env:
            - name: AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED
              value: "true"
            - name: PERSISTENCE_DATA_PATH
              value: "/var/lib/weaviate"
            - name: ENABLE_API_BASED_MODULES
              value: "true"
            - name: CLUSTER_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ENABLE_MODULES
              value: "text2vec-transformers"
            - name: TRANSFORMERS_INFERENCE_API
              value: "http://{{ include "aurora.fullname" . }}-t2v-transformers:8080"
          volumeMounts:
            - name: weaviate-data
              mountPath: /var/lib/weaviate
          readinessProbe:
            httpGet:
              path: /v1/.well-known/ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /v1/.well-known/live
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources.weaviate | nindent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: weaviate-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.persistence.weaviate.size }}
{{- end }}
